### ISSUE TITLE
Fails to read Clover test results

### ISSUE THREAD

**Issue by Saeven** [danhunsaker/clover-reporter-action#3]
Was hopeful to use this action, but it's failing with:

```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
6
TypeError: Cannot read property 'head' of undefined
7
    at main$1 (/home/runner/work/_actions/danhunsaker/clover-reporter-action/v0.2.17-clover/dist/main.js:31066:41)
8
Error: Cannot read property 'head' of undefined
```

Known issue?

**Comment by aterreno** [comment]
same fails

**Comment by eloisetaylor5693** [comment]
Getting the same error
```
Run danhunsaker/clover-reporter-action@v0.2.17-clover
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
TypeError: Cannot read property 'head' of undefined
    at main$1 (/home/runner/work/_actions/danhunsaker/clover-reporter-action/v0.2.17-clover/dist/main.js:31066:41)
Error: Cannot read property 'head' of undefined
```
